version: '3.7'

services:
  mysql:
    container_name: musicas1-mysql
    image: musicas1-mysql
    build:
      dockerfile: ./dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - musicas1-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: musicas1-app
    image: musicas1-app
    build:
      dockerfile: ./dockerfile.app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    networks:
      - musicas1-network
  react:
    depends_on:
      - app
    container_name: musicas1-react
    image: musicas1-react
    build:
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3006:3000
    networks:
      - musicas1-network

networks:
  musicas1-network:
